name: validate

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      reason:
        description: "Reason for manual trigger"
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependecies
        run: go mod download

      - name: Run unit tests with coverage
        run: make test_coverage

      - name: Install goveralls
        run: go install github.com/mattn/goveralls@latest

      - name: Upload coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
        run: goveralls -coverprofile=coverage.out -service=github
